version: '3'
services:
  front-end:
    build:
      context: ./front-end
    ports:
      - "3000:3000"

  back-end:
    build:
      context: ./back-end
    ports:
      - "8081:8081"

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: nsbnsb
      MYSQL_DATABASE: nsbDatabase
      MYSQL_USER: nsb_admin
      MYSQL_PASSWORD: nsbnsb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"

volumes:
  mysql_data: